In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("data/ontario_covid.csv")

In [19]:
df.head()

,_id,Reported Date,Confirmed Negative,Presumptive Negative,Presumptive Positive,Confirmed Positive,Resolved,Deaths,Total Cases,Total patients approved for testing as of Reporting Date,...,Number of patients in ICU on a ventilator due to COVID-19,Num. of patients in ICU on a ventilator testing positive,Num. of patients in ICU on a ventilator testing negative,Total Positive LTC Resident Cases,Total Positive LTC HCW Cases,Total LTC Resident Deaths,Total LTC HCW Deaths,Total_Lineage_B.1.1.7,Total_Lineage_B.1.351,Total_Lineage_P.1
0,1,2020-01-26,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2020-01-27,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2020-01-28,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2020-01-30,NaN,NaN,0.0,2.0,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2020-01-31,NaN,NaN,0.0,2.0,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.columns

Index(['_id', 'Reported Date', 'Confirmed Negative', 'Presumptive Negative',
       'Presumptive Positive', 'Confirmed Positive', 'Resolved', 'Deaths',
       'Total Cases',
       'Total patients approved for testing as of Reporting Date',
       'Total tests completed in the last day',
       'Percent positive tests in last day', 'Under Investigation',
       'Number of patients hospitalized with COVID-19',
       'Number of patients in ICU due to COVID-19',
       'Number of patients in ICU, testing positive for COVID-19',
       'Number of patients in ICU, testing negative for COVID-19',
       'Number of patients in ICU on a ventilator due to COVID-19',
       'Num. of patients in ICU on a ventilator testing positive',
       'Num. of patients in ICU on a ventilator testing negative',
       'Total Positive LTC Resident Cases', 'Total Positive LTC HCW Cases',
       'Total LTC Resident Deaths', 'Total LTC HCW Deaths',
       'Total_Lineage_B.1.1.7', 'Total_Lineage_B.1.351', 'Total_Lineage_P.1'],
      dtype='object')

In [21]:
df.drop(['_id', 'Confirmed Negative', 'Presumptive Negative',
       'Presumptive Positive',
       'Total patients approved for testing as of Reporting Date',
       'Total tests completed in the last day',
       'Percent positive tests in last day', 'Under Investigation',
       'Number of patients in ICU, testing negative for COVID-19',
       'Num. of patients in ICU on a ventilator testing negative',
       'Total Positive LTC Resident Cases', 'Total Positive LTC HCW Cases',
       'Total LTC Resident Deaths', 'Total LTC HCW Deaths',
       'Total_Lineage_B.1.1.7', 'Total_Lineage_B.1.351', 'Total_Lineage_P.1'], inplace=True, axis=1)

In [22]:
df.fillna(0, inplace = True)

In [23]:
df

,Reported Date,Confirmed Positive,Resolved,Deaths,Total Cases,Number of patients hospitalized with COVID-19,Number of patients in ICU due to COVID-19,"Number of patients in ICU, testing positive for COVID-19",Number of patients in ICU on a ventilator due to COVID-19,Num. of patients in ICU on a ventilator testing positive
0,2020-01-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-28,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-30,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-31,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
427,2021-04-08,28059.0,338559.0,7494.0,374112.0,1417.0,525.0,496.0,331.0,318.0
428,2021-04-09,29627.0,341200.0,7512.0,378339.0,1492.0,552.0,519.0,359.0,344.0
429,2021-04-10,30999.0,343622.0,7531.0,382152.0,1524.0,585.0,554.0,384.0,370.0
430,2021-04-11,32817.0,346239.0,7552.0,386608.0,1513.0,605.0,575.0,382.0,364.0
431,2021-04-12,34758.0,348684.0,7567.0,391009.0,1646.0,619.0,590.0,408.0,395.0

In [24]:
df.isna().sum()

Reported Date                                                0
Confirmed Positive                                           0
Resolved                                                     0
Deaths                                                       0
Total Cases                                                  0
Number of patients hospitalized with COVID-19                0
Number of patients in ICU due to COVID-19                    0
Number of patients in ICU, testing positive for COVID-19     0
Number of patients in ICU on a ventilator due to COVID-19    0
Num. of patients in ICU on a ventilator testing positive     0
dtype: int64

In [25]:
df['New_cases'] = df['Total Cases'].diff()

In [26]:
df['New_hospitalized'] = df['Number of patients hospitalized with COVID-19'].diff()

In [27]:
df['New_icu'] = df['Number of patients in ICU due to COVID-19'].diff()

In [28]:
df.fillna(0, inplace = True)

In [29]:
df

,Reported Date,Confirmed Positive,Resolved,Deaths,Total Cases,Number of patients hospitalized with COVID-19,Number of patients in ICU due to COVID-19,"Number of patients in ICU, testing positive for COVID-19",Number of patients in ICU on a ventilator due to COVID-19,Num. of patients in ICU on a ventilator testing positive,New_cases,New_hospitalized,New_icu
0,2020-01-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-28,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2020-01-30,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2020-01-31,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,2021-04-08,28059.0,338559.0,7494.0,374112.0,1417.0,525.0,496.0,331.0,318.0,3295.0,20.0,21.0
428,2021-04-09,29627.0,341200.0,7512.0,378339.0,1492.0,552.0,519.0,359.0,344.0,4227.0,75.0,27.0
429,2021-04-10,30999.0,343622.0,7531.0,382152.0,1524.0,585.0,554.0,384.0,370.0,3813.0,32.0,33.0
430,2021-04-11,32817.0,346239.0,7552.0,386608.0,1513.0,605.0,575.0,382.0,364.0,4456.0,-11.0,20.0
431,2021-04-12,34758.0,348684.0,7567.0,391009.0,1646.0,619.0,590.0,408.0,395.0,4401.0,133.0,14.0

In [30]:
df[(df['Reported Date'] <= '2020-12-31')]

,Reported Date,Confirmed Positive,Resolved,Deaths,Total Cases,Number of patients hospitalized with COVID-19,Number of patients in ICU due to COVID-19,"Number of patients in ICU, testing positive for COVID-19",Number of patients in ICU on a ventilator due to COVID-19,Num. of patients in ICU on a ventilator testing positive,New_cases,New_hospitalized,New_icu
0,2020-01-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-28,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2020-01-30,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2020-01-31,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,2020-12-27,19861.0,147178.0,4377.0,171416.0,823.0,303.0,285.0,205.0,194.0,2005.0,68.0,-4.0
326,2020-12-28,19612.0,149329.0,4414.0,173355.0,875.0,315.0,296.0,223.0,211.0,1939.0,52.0,12.0
327,2020-12-29,19891.0,151562.0,4455.0,175908.0,864.0,324.0,304.0,218.0,207.0,2553.0,-11.0,9.0
328,2020-12-30,20558.0,153799.0,4474.0,178831.0,1177.0,342.0,323.0,212.0,204.0,2923.0,313.0,18.0
329,2020-12-31,21617.0,156012.0,4530.0,182159.0,1235.0,354.0,337.0,219.0,210.0,3328.0,58.0,12.0

In [31]:
df

,Reported Date,Confirmed Positive,Resolved,Deaths,Total Cases,Number of patients hospitalized with COVID-19,Number of patients in ICU due to COVID-19,"Number of patients in ICU, testing positive for COVID-19",Number of patients in ICU on a ventilator due to COVID-19,Num. of patients in ICU on a ventilator testing positive,New_cases,New_hospitalized,New_icu
0,2020-01-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-28,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2020-01-30,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2020-01-31,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,2021-04-08,28059.0,338559.0,7494.0,374112.0,1417.0,525.0,496.0,331.0,318.0,3295.0,20.0,21.0
428,2021-04-09,29627.0,341200.0,7512.0,378339.0,1492.0,552.0,519.0,359.0,344.0,4227.0,75.0,27.0
429,2021-04-10,30999.0,343622.0,7531.0,382152.0,1524.0,585.0,554.0,384.0,370.0,3813.0,32.0,33.0
430,2021-04-11,32817.0,346239.0,7552.0,386608.0,1513.0,605.0,575.0,382.0,364.0,4456.0,-11.0,20.0
431,2021-04-12,34758.0,348684.0,7567.0,391009.0,1646.0,619.0,590.0,408.0,395.0,4401.0,133.0,14.0

In [32]:
df.to_csv('data/ON_covid.csv', index=False)